### ISSUE TITLE
List of Supported Hardware and Software is broken in the Installation page

### ISSUE THREAD

**Issue by jaykolla** [ROCm/hip-python#41]
This page is broken, users do not have a way to find out Supported HW and SW https://docs.amd.com/en/latest/release/gpu_os_support.html

From this page the HW/SW supported page is broken, 
https://rocm.docs.amd.com/projects/hip-python/en/latest/user_guide/0_install.html#supported-hardware.

**Comment by domcharrier** [comment]
Thanks for reporting. The new correct ROCm HW support URL seems to be:
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#

**Comment by jaykolla** [comment]
can we have the broken links removed or the redirections updated on that page? thank you.

**Comment by ppanchad-amd** [comment]
@jaykolla redirection is updated. Closing ticket. Thanks!
